Add basic functionality
artembiserov/active_storage pull request #1
Opened 2016-12-21 12:51 UTC by artembiserov

Add ability to find and save records.

2016-12-25 14:27 UTC, tz3 commented on spec/active_storage_spec.rb
> +require "pry"
Какой смысл оставлять это здесь?

2016-12-25 14:31 UTC, tz3 commented
предпочтительнее использовать одинарные кавычки для строк нежели двойные,  подробнее [тут](https://github.com/bbatsov/ruby-style-guide#strings)

2016-12-25 14:40 UTC, tz3 commented on README.md
> +  include ActiveStorage
Мне кажется, было бы полезным выделить базовый класс и в него включить ваш модуль по хранению.

2016-12-25 14:40 UTC, tz3 commented on spec/active_storage_spec.rb
> +      it { is_expected.to eq 2 }
👍

2016-12-25 14:41 UTC, tz3 commented
Вы можете проверить ruby style с помощью [rubocop](https://github.com/bbatsov/rubocop)

2016-12-26 07:44 UTC, artembiserov commented
@tz3 https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
Здесь указано, что есть два стиля, одинаково хороших. Главное в одном проекте использовать только один стиль.

2016-12-26 08:39 UTC, AndreyNenashev commented on spec/fixtures/product.rb
> +    "./spec/fixtures"
Конфигурирование бд лучше сделать внутри `ActiveStorage`. Иначе, если бы было 10 классов, то пришлось бы 10 раз писать одно и то же для каждого класса.

2016-12-26 08:41 UTC, AndreyNenashev commented
Еще было бы здорово сделать базовые ассоциации типа belongs_to, has_many

2016-12-26 08:43 UTC, artembiserov commented on spec/fixtures/product.rb
> +    "./spec/fixtures"
оно там есть внутри, просто для спеков переопределил

2016-12-26 08:43 UTC, artembiserov commented
@AndreyNenashev хорошо

2016-12-26 08:47 UTC, AndreyNenashev commented on lib/active_storage.rb
> +        Product.new(params)
Прям так? внутри гема захардкоженный `Product`?

2016-12-26 08:51 UTC, AndreyNenashev commented on spec/fixtures/product.rb
> +    "./spec/fixtures"
Ок

2016-12-26 08:52 UTC, artembiserov commented on lib/active_storage.rb
> +        Product.new(params)
не заметил, исправил :)

2016-12-26 09:13 UTC, AndreyNenashev commented on spec/fixtures/product.rb
> +  attributes :title, :body
Это можно сделать по умолчанию внутри ActiveStorage, чтобы атрибуты определялись на основе таблицы бд, а не вручную. Как в рельсовом ActiveRecord.

2016-12-26 10:21 UTC, artembiserov commented on spec/fixtures/product.rb
> +  attributes :title, :body
Я задумывал менять структуру csv в модели. Реализовал правда только создание.

2016-12-26 19:04 UTC, edikgat commented on README.md
> +  include ActiveStorage
ихмо подход с миксиной тоже имеет право на жизнь в этом случае

2016-12-26 19:59 UTC, edikgat commented
а еще нужна внятная система исключений что-бы можно было певесить rescue на базовый класс твоих исключений и отловить их все

2016-12-26 19:59 UTC, edikgat requested changes

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage.rb
> +  class_methods do
так делать не правильно
тк этот подход убивает возможность
1) использовать super
2) вообще хоть как то переопределить метод с тем же именем что есть тут

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage.rb
> +        attr_accessor(*@@attributes)
и тут тоже та же проблема с супер

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage.rb
> +    def connect
а что если такой папки нет итп
те нужно предусмотреть систему исключений

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage.rb
> +    table = CSV.table(self.class.storage_path, col_sep: ";", headers: true)
а что насчет возможности конфигурирования

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage.rb
> +    self.id = Time.current.to_f
для уверенности лучше еще добавить случайное число

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage.rb
> +    def all
для таких штук есть alias_method

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage/relation.rb
> +    def count
delegate

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage/relation.rb
> +        attrs.inject(true) { |result, (key, value)| result && record.public_send(key) == value }
а если передали не хэш?

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage/version.rb
> +  VERSION = "0.1.0".freeze
современные руби и так это делают

2016-12-26 19:59 UTC, edikgat commented on spec/fixtures/product.rb
> +  attributes :title, :body
это уже не актив рекорд паттерн
актив рекорд это именно когда
каждый экземпляр данного класса соответствует одной записи таблицы;
при создании нового экземпляра класса (и заполнении соответствующих полей) в таблицу добавляется новая запись;
при чтении полей объекта считываются соответствующие значения записи таблицы баз данных;
при изменении (удалении) какого-либо объекта изменяется (удаляется) соответствующая ему запись.

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage.rb
>  module ActiveStorage
нужно еще реализовать ispect метод чтобы выводилось что-то адекватное при использовании класса

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage.rb
> +    CSV.open(self.class.storage_path, "ab", col_sep: ";") do |csv|
все подобные вызовы должны быть как минимум в отдельном методе - но по хорошему это отдельный класс
реализующий работу с таблицами

при этом этот класс должен быть реализован так чтобы его можно было сменить и тем тамым использовать др хранилище

2016-12-26 19:59 UTC, edikgat commented on lib/active_storage.rb
> +    def records
хорошо бы вынести подобный ф-ционал в отдельный класс

2016-12-26 20:06 UTC, edikgat commented on lib/active_storage/relation.rb
> +module ActiveStorage
было бы круто чтобы эта штука возвращала что-то вроде лямбд
те те чтобы была возможность того чтобы поиск шел не сразу

2016-12-26 20:08 UTC, edikgat commented on lib/active_storage.rb
> +    def database_path
вынести в конфигурацию

2016-12-26 20:08 UTC, edikgat commented on lib/active_storage.rb
> +      CSV.open(storage_path, "ab", col_sep: ";") do |csv|
col_sep в конфигурацию

2016-12-26 20:13 UTC, edikgat commented on lib/active_storage/version.rb
> +  VERSION = "0.1.0".freeze
если для экономии памяти - то это уже оптимизировано  в современных рубях
если чтобы версию не меняли - то думаю - это излишне

2016-12-26 20:15 UTC, edikgat commented on config/rubocop.yml
> +  EnforcedStyle: double_quotes
ихмо одинарные понятнее показывают что данную строку не планируется модифицировать при инициализации
но - каждому свое

2016-12-26 20:18 UTC, artembiserov commented on lib/active_storage/version.rb
> +  VERSION = "0.1.0".freeze
rubocop выдал варнинг

2016-12-26 20:19 UTC, edikgat commented on spec/fixtures/product.rb
> +    "./spec/fixtures"
в идеале можно сделать возможность менять эти параметры для каждого класса - но значения по умолчанию быть должны

2016-12-26 20:25 UTC, artembiserov commented on spec/fixtures/product.rb
> +  attributes :title, :body
вроде бы все пункты выполняются?

2016-12-26 20:34 UTC, edikgat commented on lib/active_storage/version.rb
> +  VERSION = "0.1.0".freeze
ок )
это второй гем который я встречаю где VERSION фризится
первый - это сам rubocop

2016-12-26 20:43 UTC, edikgat commented on spec/fixtures/product.rb
> +  attributes :title, :body
при чтении полей объекта считываются соответствующие значения записи таблицы баз данных;
это в том числе о том что поля в базе хранятся, в том числе структура полей - 
в случае этого гема если не инициировать поле то оно не прочитается

в прочем, думаю, не стоит на этом заморачиваться
это не очень критично  и к тому же придется создавать что-то вроде конфигурации таблиц для цсв

2016-12-27 15:47 UTC, edikgat requested changes

2016-12-27 15:47 UTC, edikgat commented on spec/fixtures/sku.rb
> +  belongs_to :product
а где реализация?

2016-12-27 15:47 UTC, edikgat commented on lib/active_storage/store.rb
> +      table = CSV.table(self.class.storage_path, col_sep: ";", headers: true)
всю работу с таблицами нужно вынести в отдельный КЛАСС, не модуль
этот класс по хорошему должен быть выполнен с использованием паттерна СТРАТЕГИЯ -https://en.wikipedia.org/wiki/Strategy_pattern

тогда данный - или подобный модуль должен быть выполнен в паттерне КОНТЕКСТ и иметь ссылку на стратегию. - эту ссылку должна быть возможность менять в конфигураторе

2016-12-27 15:47 UTC, edikgat commented on lib/active_storage/querying.rb
> +      table = CSV.read(storage_path, col_sep: ";", headers: true)
всю работу с таблицами в отдельный класс
всю конфигурацию в конфигуратор

2016-12-27 15:47 UTC, edikgat commented on lib/active_storage/store.rb
> +      CSV.open(self.class.storage_path, "ab", col_sep: ";") do |csv|
и это тоже в отдельный класс

2016-12-27 17:31 UTC, artembiserov commented on spec/fixtures/sku.rb
> +  belongs_to :product
дня через два продолжу

2017-01-11 12:48 UTC, edikgat requested changes

2017-01-11 12:48 UTC, edikgat commented on lib/active_storage.rb
> +require "pry"
это еще тут зачем?
у тебя прай в зависимостях отсутствует, и эта строчка вызовет эксепшен если в проекте, где твой гем используется его нет

2017-01-11 12:48 UTC, edikgat commented on lib/active_storage.rb
> +    self.id = params["id"]
а если id не передан?

2017-01-11 12:48 UTC, edikgat commented on lib/active_storage.rb
> +    raise ArgumentError, "You must pass an hash as an argument" unless params.is_a?(Hash)
это дублирование

2017-01-11 12:48 UTC, edikgat commented on lib/active_storage/adapters/csv_adapter.rb
> +      def connect(klass)
делать открытие цсв на каждый чих не очень оправданно
лучше сделать в духе

```
def connect(klass, force_reload: false);
 return if @connected && !force_reload
  @connected ||= begin do
    ...
    true
  end
end
```

2017-01-11 12:48 UTC, edikgat commented on lib/active_storage/adapters/csv_adapter.rb
> +      def connect(klass)
этот трюк лючше провести в ActiveStorage

2017-01-11 12:48 UTC, edikgat commented on lib/active_storage/association.rb
> +      define_method name do
тут по хорошему лучше создавать метод не непосредственно в классе, а в анонимном модуле, который инклюдится в класс
типа
```
m = Module.new do
  define_method name do
   ...
  end
end
self.include(m)
```
в этом случае можно уже внутри класса пользователя
использовать super для вызова сгенеренных методов

2017-01-11 13:07 UTC, artembiserov commented on lib/active_storage.rb
> +    self.id = params["id"]
Тогда он будет пустым и это новая запись. Этот момент нужно перенести в метод, где считываются данные из csv.

2017-01-13 07:30 UTC, merged